name: Publish Docker Image

on:
  push:
    branches: [main]
    
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on : ubuntu:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Extract meta data (tags, labels) for Docker
        id: meta
        uses: docker/metadata-actions@v3
        with:
          images: rohitkumar/nodeapp

      - name: Build and Push Docker image
        uses: docker/build-push-actions@v3
        with:
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}

  
      

